server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bank-account
          uri: lb://bank-account
          predicates:
            - Path=/account/**
        - id: personal-customer
          uri: lb://personal-customer
          predicates:
            - Path=/customer/**
