server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb+srv://patriciotinez:PJeqNmcI37QE9gVY@bank-reactivedb.mn3f7rr.mongodb.net/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
